author: mnc
title: [mnc](https://twitter.com/__mnc90)の書きなぐりメモ
description: はてブロに書くほどではない内容を書きなぐっていきます。AWS,Rails,Ruby,React,スタートアップ,マネジメント,キャリアとか
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
twitter_username: __mnc90
github_username: mnc
